#!/usr/bin/env perl
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin";

$ENV{MOJO_LISTEN} //= "http://127.0.0.1:3000";

# Start command line interface for application
require Mojolicious::Commands;
my $app = Mojolicious::Commands->start_app("TrsrDB::HTTP");
